#!/bin/sh
# forked from luke smith
# https://github.com/LukeSmithxyz/voidrice/blob/f853f1884a8f0c244765192dc6f5a910a7e2b8e5/.local/bin/dmenuunicode

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/.local/share/chars/* | dmenu -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# Show a message that the emoji has been copied.
printf "%s" "$chosen" | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard." &
