#!/bin/sh

# Find pass directory
prefix=${PASSWORD_STORE_DIR-~/.password-store}

# Locate all password files, and select with dmenu
chosen=$(find "$prefix" -type f -name '*.gpg' 2>/dev/null | \
                 sed -e "s|^$prefix/||" -e 's/\.gpg$//' | 
		 dmenu -i -l 30 "$@")

# Exit if none chosen
[ -z $chosen ] && exit

pass show -c "$chosen" 2>/dev/null
notify-send "'$chosen' copied to clipboard." &
