#!/bin/sh

# Use PASSWORD_STORE_DIR if set, otherwise default to ~/.password-store
store_dir="${PASSWORD_STORE_DIR:-${HOME}/.password-store}"

# Locate and select pass entry
chosen=$(find "${store_dir}" -type f -name '*.gpg' 2>/dev/null | \
          sed -e "s|^${store_dir}/||" -e 's/\.gpg$//' | \
          dmenu -i -l 30)

# Exit if no selection made
[ -z "${chosen}" ] && exit

# Copy to clipboard
case $1 in
	-o) pass otp -c "$chosen" ;; # Copy OTP
	-u) pass show -c2 "$chosen" ;; # Copy username
	-p) pass show -c "$chosen" ;; # Copy password
esac >/dev/null 2>&1
